apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: j0gcfgiri-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-de413252c4.8vpp.p3.openshiftapps.com/rhtap/rhtap-qe:3f7b5c90f72d5719705f6894b4b9285a1e982003@sha256:320a4c1bdc95394f99732cd89107cc5c410197dbbbd67ad4f00ef5732d1769a2
          name: container-image
