apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: j0gcfgiri-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/j0gcfgiri-java-springboot-gitops